# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20170912_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('ordinal', models.IntegerField(default=0)),
                ('premiered_on', models.DateField()),
                ('encored_on', models.DateField()),
            ],
        ),
    ]
