# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20170912_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='encored_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='premiered_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
