# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmlocation',
            name='name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmlocation',
            name='fun_facts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
